version: "3.8"

services:
  frontend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-aidoodle:latest
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-aidoodle:latest
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ai_doodle
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
