name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/build-frontend.yml

env:
  IMAGE_NAME: frontend-aidoodle

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Build frontend Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push frontend image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/,,')
          [ "$VERSION" == "main" ] && VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: SSH into VM and redeploy frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_DEPLOY_KEY }}
          script: |
            cd ~/project-ai-doodle
            docker-compose stop frontend
            docker-compose rm -f frontend
            docker-compose pull frontend
            docker-compose up -d --no-deps --force-recreate frontend
