name: Build and Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/build-backend.yml

env:
  IMAGE_NAME: backend-aidoodle

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        run: |
          cd backend
          docker build --no-cache . -t $IMAGE_NAME

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push backend image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/,,')
          [ "$VERSION" == "main" ] && VERSION=latest
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: SSH into VM and redeploy backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_DEPLOY_KEY }}
          script: |
            cd ~/project-ai-doodle
            docker-compose stop backend
            docker-compose rm -f backend
            docker-compose pull backend
            docker-compose up -d backend

      - name: Check code is up to date
        run: docker run --rm $IMAGE_NAME ls -l /app
