name: Express Backend CI

on:
  push:
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ai_doodle
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: ai_doodle
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: localhost
      DB_PORT: 5432
      SESSION_SECRET: tempsecret
      FRONTEND_URL: http://localhost:5173

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start Express server
        run: node app.js > server.log 2>&1 &

      - name: Wait for server to be ready
        run: wait-on http://localhost:3000/api/hello

      - name: Test /api/hello
        run: curl --fail http://localhost:3000/api/hello
