# This is a basic workflow to help you get started with Actions

name: Run Express Server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    defaults:
      run:
        working-directory: ./backend
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start Express Server (in background)
        run: |
          node app.js &
      
      - name: Wait for server to be ready
        run: wait-on http://localhost:3000/api/hello

      - name: Test API
        run: curl --fail http://localhost:3000/api/hello
